/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dase.gestorcorreos.componentes;

import com.dase.gestorcorreos.dto.EmailDto;
import com.dase.gestorcorreos.service.impl.EmailService;
import javax.mail.MessagingException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 *
 * @author Alexander Elias
 */
@Service
public class EmailNotificacion {

    @Autowired
    EmailService email;

    public boolean notificacionInvitacion(String emailDestino, String asunto, String nombreTablero) {

        String content = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\"xmlns:o=\"urn:schemas-microsoft-com:office:office\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"x-apple-disable-message-reformatting\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "<title></title><style type=\"text/css\">@media only screen and (min-width: 620px) {.u-row {width: 600px !important;}.u-row .u-col {vertical-align: top;}.u-row .u-col-50 {width: 300px !important;}.u-row .u-col-100 {width: 600px !important;}}@media (max-width: 620px) {.u-row-container {\n"
                + "max-width: 100% !important;\n"
                + "padding-left: 0px !important;\n"
                + "padding-right: 0px !important;\n"
                + "}\n"
                + ".u-row .u-col{\n"
                + "min-width: 320px !important;\n"
                + "max-width: 100% !important;\n"
                + "display: block !important;\n"
                + "}\n"
                + ".u-row{\n"
                + "width: calc(100% - 40px) !important;\n"
                + "}\n"
                + ".u-col{\n"
                + "width: 100% !important;\n"
                + "}\n"
                + ".u-col>div{\n"
                + "margin: 0 auto;\n"
                + "}\n"
                + "}\n"
                + "body{\n"
                + "margin: 0;\n"
                + "padding: 0;\n"
                + "}\n"
                + "table,\n"
                + "tr,\n"
                + "td{\n"
                + "vertical-align: top;\n"
                + "border-collapse: collapse;\n"
                + "}\n"
                + "p{\n"
                + "margin: 0;\n"
                + "}\n"
                + ".ie-container table,\n"
                + ".mso-container table {\n"
                + "table-layout: fixed;\n"
                + "}\n"
                + "* {\n"
                + "line-height: inherit;\n"
                + "}\n"
                + "a[x-apple-data-detectors='true'] {\n"
                + "color: inherit !important;\n"
                + "text-decoration: none !important;\n"
                + "}\n"
                + "table,\n"
                + "td {\n"
                + "color: #000000;\n"
                + "}\n"
                + "\n"
                + "#u_body a {\n"
                + "color: #161a39;\n"
                + "text-decoration: underline;\n"
                + "}\n"
                + "</style>\n"
                + "<link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "</head>\n"
                + "<body class=\"clean-body u_body\"style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #f9f9f9;color: #000000\">\n"
                + "<table id=\"u_body\"\n"
                + "style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #f9f9f9;width:100%\"\n"
                + "cellpadding=\"0\" cellspacing=\"0\">\n"
                + "<tbody>\n"
                + "<tr style=\"vertical-align: top\">\n"
                + "<td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\"><div class=\"u-row\"style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                + "<div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\"><tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f9f9f9;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "<tbody>\n"
                + "<tr style=\"vertical-align: top\">\n"
                + "<td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "<span>&#160;</span>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "<div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #02395c;\">\n"
                + "<div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:16px 10px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "<p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 28px; line-height: 39.2px; color: #ffffff; font-family: Lato, sans-serif;\">Invitación a Tablero: " + nombreTablero + "</span></p>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "<div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\n"
                + "<div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Hola,</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"> </p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Se te ha invitado a participar en el tablero: <strong>" + nombreTablero + "</strong>. </span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"> </p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Puedes acceder mediante tu correo electrónico al siguiente enlace: </span></p>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div align=\"left\">\n"
                + "<a href=\"https://app-organizador-tareas.herokuapp.com/invitado\" target=\"_blank\" class=\"v-button\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #02395c; border-radius: 1px;-webkit-border-radius: 1px; -moz-border-radius: 1px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\n"
                + "<span style=\"display:block;padding:15px 40px;line-height:120%;\"><span style=\"font-size: 18px; line-height: 21.6px;\">Ir a la página</span></span>\n"
                + "</a>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"color: #888888; font-size: 14px; line-height: 19.6px;\"><em><span style=\"font-size: 16px; line-height: 22.4px;\">¡Te invitamos a registrarte en nuestra página para aprovechar todas las funciones disponibles!</span></em></span><br /><span style=\"color: #888888; font-size: 14px; line-height: 19.6px;\"><em><span style=\"font-size: 16px; line-height: 22.4px;\"> </span></em></span></p>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "<div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #02395c;\">\n"
                + "<div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 16px; line-height: 22.4px; color: #ecf0f1;\">Grupo 4</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 14px; line-height: 19.6px; color: #ecf0f1;\">Análisis de Sistemas II</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 14px; line-height: 19.6px; color: #ecf0f1;\">Ingeniería en Sistemas</span></p>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div align=\"center\">\n"
                + "<div style=\"display: table; max-width:187px;\">\n"
                + "</div>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div style=\"line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
                + "<p style=\"line-height: 140%; font-size: 14px;\"><span style=\"font-size: 12px; line-height: 16.8px;\"><span style=\"color: #ecf0f1; line-height: 16.8px; font-size: 12px;\"><span style=\"line-height: 16.8px; font-size: 12px;\">Organizador De Tareas | Copyright @ 2022</span></span></span></p>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\">\n"
                + "<div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #1c103b;\">\n"
                + "<div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #1c103b;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "<tbody>\n"
                + "<tr style=\"vertical-align: top\">\n"
                + "<td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "<span>&#160;</span>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "<div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                + "<div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "<div style=\"height: 100%;width: 100% !important;\">\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px 30px 20px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "<div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</body>\n"
                + "</html>";

        EmailDto emailsend = new EmailDto(
                emailDestino,
                asunto,
                content
        );

        try {
            this.email.sendWithAttach(emailsend);
            return true;

        } catch (MessagingException e) {
            return false;
        }

    }

    public boolean notificacionRegistro(String emailDestino, String asunto) {

        String content = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "<head>\n"
                + "\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "  <meta name=\"x-apple-disable-message-reformatting\">\n"
                + "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "  <title></title>\n"
                + "  \n"
                + "    <style type=\"text/css\">\n"
                + "      @media only screen and (min-width: 620px) {\n"
                + "  .u-row {\n"
                + "    width: 600px !important;\n"
                + "  }\n"
                + "  .u-row .u-col {\n"
                + "    vertical-align: top;\n"
                + "  }\n"
                + "\n"
                + "  .u-row .u-col-50 {\n"
                + "    width: 300px !important;\n"
                + "  }\n"
                + "\n"
                + "  .u-row .u-col-100 {\n"
                + "    width: 600px !important;\n"
                + "  }\n"
                + "\n"
                + "}\n"
                + "\n"
                + "@media (max-width: 620px) {\n"
                + "  .u-row-container {\n"
                + "    max-width: 100% !important;\n"
                + "    padding-left: 0px !important;\n"
                + "    padding-right: 0px !important;\n"
                + "  }\n"
                + "  .u-row .u-col {\n"
                + "    min-width: 320px !important;\n"
                + "    max-width: 100% !important;\n"
                + "    display: block !important;\n"
                + "  }\n"
                + "  .u-row {\n"
                + "    width: calc(100% - 40px) !important;\n"
                + "  }\n"
                + "  .u-col {\n"
                + "    width: 100% !important;\n"
                + "  }\n"
                + "  .u-col > div {\n"
                + "    margin: 0 auto;\n"
                + "  }\n"
                + "}\n"
                + "body {\n"
                + "  margin: 0;\n"
                + "  padding: 0;\n"
                + "}\n"
                + "\n"
                + "table,\n"
                + "tr,\n"
                + "td {\n"
                + "  vertical-align: top;\n"
                + "  border-collapse: collapse;\n"
                + "}\n"
                + "\n"
                + "p {\n"
                + "  margin: 0;\n"
                + "}\n"
                + "\n"
                + ".ie-container table,\n"
                + ".mso-container table {\n"
                + "  table-layout: fixed;\n"
                + "}\n"
                + "\n"
                + "* {\n"
                + "  line-height: inherit;\n"
                + "}\n"
                + "\n"
                + "a[x-apple-data-detectors='true'] {\n"
                + "  color: inherit !important;\n"
                + "  text-decoration: none !important;\n"
                + "}\n"
                + "\n"
                + "table, td { color: #000000; } #u_body a { color: #161a39; text-decoration: underline; }\n"
                + "    </style>\n"
                + "  \n"
                + "  \n"
                + "\n"
                + "<link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #f9f9f9;color: #000000\">\n"
                + "  <table id=\"u_body\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #f9f9f9;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\n"
                + "  <tbody>\n"
                + "  <tr style=\"vertical-align: top\">\n"
                + "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\n"
                + "\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\">\n"
                + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                + "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                + "  \n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f9f9f9;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "    <tbody>\n"
                + "      <tr style=\"vertical-align: top\">\n"
                + "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "          <span>&#160;</span>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "    </tbody>\n"
                + "  </table>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "  </div>\n"
                + "</div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "\n"
                + "\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #02395c;\">\n"
                + "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                + "  \n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:16px 10px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "    <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 28px; line-height: 39.2px; color: #ffffff; font-family: Lato, sans-serif;\">¡Gracias Por Registrarte!</span></p>\n"
                + "  </div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "  </div>\n"
                + "</div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "\n"
                + "\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\n"
                + "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\n"
                + "  \n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Hola,</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"> </p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Gracias por registrarte a nuestro <strong>Organizador de Tareas</strong>. </span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"> </p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Puedes iniciar sesión presionando el siguiente botón: </span></p>\n"
                + "  </div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "\n"
                + "<div align=\"left\">\n"
                + "\n"
                + "    <a href=\"https://app-organizador-tareas.herokuapp.com/login\" target=\"_blank\" class=\"v-button\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #02395c; border-radius: 1px;-webkit-border-radius: 1px; -moz-border-radius: 1px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\n"
                + "      <span style=\"display:block;padding:15px 40px;line-height:120%;\"><span style=\"font-size: 18px; line-height: 21.6px;\">Iniciar</span></span>\n"
                + "    </a>\n"
                + "\n"
                + "</div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"color: #888888; font-size: 14px; line-height: 19.6px;\"><em><span style=\"font-size: 16px; line-height: 22.4px;\">Por favor ignora este correo si no te has registrado.</span></em></span><br /><span style=\"color: #888888; font-size: 14px; line-height: 19.6px;\"><em><span style=\"font-size: 16px; line-height: 22.4px;\"> </span></em></span></p>\n"
                + "  </div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "\n"
                + "\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #02395c;\">\n"
                + "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "\n"
                + "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "\n"
                + "  \n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 16px; line-height: 22.4px; color: #ecf0f1;\">Grupo 4</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 14px; line-height: 19.6px; color: #ecf0f1;\">Análisis de Sistemas II</span></p>\n"
                + "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 14px; line-height: 19.6px; color: #ecf0f1;\">Ingeniería en Sistemas</span></p>\n"
                + "  </div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "<div align=\"center\">\n"
                + "  <div style=\"display: table; max-width:187px;\">\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <div style=\"line-height: 140%; text-align: center; word-wrap: break-word;\">\n"
                + "    <p style=\"line-height: 140%; font-size: 14px;\"><span style=\"font-size: 12px; line-height: 16.8px;\"><span style=\"color: #ecf0f1; line-height: 16.8px; font-size: 12px;\"><span style=\"line-height: 16.8px; font-size: 12px;\">Organizador De Tareas | Copyright @ 2022</span></span></span></p>\n"
                + "  </div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "  </div>\n"
                + "</div>\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "\n"
                + "\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\">\n"
                + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #1c103b;\">\n"
                + "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #1c103b;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "    <tbody>\n"
                + "      <tr style=\"vertical-align: top\">\n"
                + "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\n"
                + "          <span>&#160;</span>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "    </tbody>\n"
                + "  </table>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "\n"
                + "\n"
                + "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\n"
                + "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\n"
                + "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\n"
                + "\n"
                + "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\n"
                + "  <div style=\"height: 100%;width: 100% !important;\">\n"
                + "\n"
                + "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px 30px 20px;font-family:'Lato',sans-serif;\" align=\"left\">\n"
                + "        \n"
                + "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\n"
                + "    \n"
                + "  </div>\n"
                + "\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "    </div>\n"
                + "  </div>\n"
                + "</div>\n"
                + "\n"
                + "    </td>\n"
                + "  </tr>\n"
                + "  </tbody>\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        EmailDto emailsend = new EmailDto(
                emailDestino,
                asunto,
                content
        );

        try {
            this.email.sendWithAttach(emailsend);
            return true;

        } catch (MessagingException e) {
            return false;
        }

    }

}
